services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - "8080:80"
    links:
      - wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    env_file: .env
    volumes:
      - ./data/html:/var/www/html
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST:  db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}

  db:
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    restart: unless-stopped
    links:
      - db:mysql
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}